import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:path_provider/path_provider.dart';
import 'package:isar/isar.dart';
import 'package:metals_tracker/core/theme.dart';
import 'package:metals_tracker/presentation/providers/theme_provider.dart';
import 'package:metals_tracker/data/local/isar_transaction.dart';
import 'package:metals_tracker/presentation/screens/dashboard_screen.dart';
import 'package:metals_tracker/presentation/providers/auth_provider.dart';
import 'package:metals_tracker/presentation/screens/login_screen.dart';

// 1. Create a global provider for Isar so the rest of the app can access it
final isarProvider = Provider<Isar>((ref) {
  throw UnimplementedError('Isar must be initialized before use');
});

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Supabase
  await Supabase.initialize(
    url: 'https://gyhkwznimfmbwqfispni.supabase.co',
    anonKey: 'sb_publishable_j9y-35fJVLeQQvsUq0FSfQ_AthG74ry',
  );

  // 3. Initialize Isar Local Database
  final dir = await getApplicationDocumentsDirectory();
  final isar = await Isar.open(
    [IsarTransactionSchema], // This schema was generated by build_runner
    directory: dir.path,
  );

  runApp(
    // 4. Inject the initialized Isar instance into Riverpod
    ProviderScope(
      overrides: [
        isarProvider.overrideWithValue(isar),
      ],
      child: const MetalsTrackerApp(),
    ),
  );
}

class MetalsTrackerApp extends ConsumerWidget {
  const MetalsTrackerApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authStateProvider);
    final currentThemeMode = ref.watch(themeProvider);

    return MaterialApp(
      title: 'Metals Tracker',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: currentThemeMode,
      home: authState.when(
        data: (state) {
          if (state.session != null) {
            return const DashboardScreen();
          }
          return const LoginScreen();
        },
        loading: () =>
            const Scaffold(body: Center(child: CircularProgressIndicator())),
        error: (err, stack) =>
            Scaffold(body: Center(child: Text('Error: $err'))),
      ),
    );
  }
}
